spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 788089872442-kj19jkt8gjeh6rpc6c1jlivm8n89714g.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  datasource:
    url: jdbc:mysql://localhost:3307/security_db
    username: admin
    password: h6626070
  jpa:
    hibernate:
      ddl-auto: update
