version: "3.8"

services:

  accounts-service:
    container_name: accounts-service
    build:
      context: ./accounts-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - microservices-sample-network
    depends_on:
      - config-server
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: optional:configserver:http://localhost:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/

  loans-service:
    container_name: loans-service
    build:
      context: ./loans-service
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    networks:
      - microservices-sample-network
    depends_on:
      - config-server
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: optional:configserver:http://localhost:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/

  cards-service:
    container_name: cards-service
    build:
      context: ./cards-service
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - microservices-sample-network
    depends_on:
      - config-server
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: optional:configserver:http://localhost:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/

  config-server:
    container_name: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8071:8071"
    networks:
      - microservices-sample-network

  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8070:8070"
    networks:
      - microservices-sample-network
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: optional:configserver:http://localhost:8071

networks:
  microservices-sample-network: